### PR TITLE
Added hex transparency

### LINKED ISSUE #16: [Feature request] transparency with hex codes
Currently, transparency doesn't work with hex codes, relevant part of README:
> Transparency Mode
 Press t to toggle Transparency Slider. While this mode is active, you will only be able to output the color as rgba() or hsla(). If you want to output as HEX, press t to get out of Transparency Mode, and you'll be able to press o to output your color as HEX.

Could it be possible for this to also work with hex? (because exiting transparency mode of course loses the transparency info)
It's pretty standard for the transparency value to be at the back of the hexcode, going from 00 to FF. (I know there are outliers, but I would rather have a way to add transparency then no way at all).

### LINKED ISSUE #18: [Bug] Pressing ctrl+c while in the menu opens another one
image
:smiley:
Ill try and resolve this in my pr as well (if you don't mind)

### PR DESCRIPTION
**Pull request by lars-vc**
Added hex transparency to the back of hex codes
closes #16 
closes #18

### CODE REVIEW

**Comment by ziontee113** [comment]
Hi @lars-vc , thank you very much for submitting the PR.
I tried it out and things are looking good.

One small issue is that the Transparent HEX value should be at the beginning instead of at the end? According to:
https://stackoverflow.com/a/23201304/19205063
https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

But there are information like this
https://webtools.fineaty.com/ColorInfo/FFFFFF00/en/Information-about-the-FFFFFF00-color.html

I'm unfamiliar with Transparent HEX colors so I can't tell :smile:. What do you think about putting Transparent HEX information at the beginning or at the end? Thank you :)

**Comment by ziontee113** [comment]
Also I forgot about when you open the Color Picker when your cursor is on a color, the Color Picker should pick up the color under your cursor. Maybe we can add the feature for Transparent HEX colors in the future?

**Comment by lars-vc** [comment]
> Hi @lars-vc , thank you very much for submitting the PR. I tried it out and things are looking good.
> 
> One small question I have is that the Transparent HEX value should be at the beginning instead of at the end? According to: https://stackoverflow.com/a/23201304/19205063 https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
> 
> But there are information like this https://webtools.fineaty.com/ColorInfo/FFFFFF00/en/Information-about-the-FFFFFF00-color.html
> 
> I'm unfamiliar with Transparent HEX colors so I can't tell 😄. What do you think about putting Transparent HEX information at the beginning or at the end? Thank you :)

It is a bit of a toss up, but CSS uses at the back (https://stackoverflow.com/questions/1751263/hex-colors-numeric-representation-for-transparent). So that's why I picked at the back.

**Comment by lars-vc** [comment]
> Also I forgot about when you open the Color Picker when your cursor is on a color, the Color Picker should pick up the color under your cursor. Maybe we can add the feature for Transparent HEX colors in the future?

Ah I forgot about this, Ill fix it tmrw!

**Comment by ziontee113** [comment]
>Ah I forgot about this, Ill fix it tmrw!
Thank you very much. I'm sorry in advance because that part of the code base is a bit amateurish :smile:

**Comment by lars-vc** [comment]
Added!

**Comment by ziontee113** [comment]
Thank you very much @lars-vc for the amazing PR :smile:

**Pull request merged**
